module.exports = {
  "@types/axios": "^0.14.0",
  "@types/node": "^14.14.6",
  "@persagy2/eslint-plugin": "*0.1.4-dev.2",
  "@typescript-eslint/eslint-plugin": "^5.42.0",
  "@typescript-eslint/parser": "^5.42.0",
  "@vue/cli-plugin-babel": "~5.0.0",
  "@vue/cli-plugin-eslint": "~5.0.0",
  "@vue/cli-plugin-router": "~5.0.0",
  "@vue/cli-plugin-typescript": "~5.0.0",
  "@vue/cli-plugin-vuex": "~5.0.0",
  "@vue/cli-service": "~5.0.0",
  "babel-plugin-component": "^1.1.1",
  eslint: "^8.27.0",
  "eslint-plugin-unicorn": "^44.0.2",
  "eslint-plugin-vue": "^9.7.0",
  less: "^4.0.0",
  "less-loader": "^8.0.0",
  prettier: "^2.4.1",
  typescript: "~4.5.5",
  "vue-template-compiler": "^2.6.14",
  "meri-design": "^1.4.0",
  "webpack-version-zip": "^2.0.0",
};
